services:
  vt-back:
    build:
      context: ./vt-back
      dockerfile: Dockerfile
    container_name: vaulteek-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./vt-back/gcp-key.json:/app/gcp-key.json:ro
    restart: unless-stopped

  vt-front:
    build:
      context: ./vt-front
      dockerfile: Dockerfile
    container_name: vaulteek-frontend
    ports:
      - "4000:4000"
    depends_on:
      - vt-back
    restart: unless-stopped


